/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iosdevlog_a26jni_Jni */

#ifndef _Included_com_iosdevlog_a26jni_Jni
#define _Included_com_iosdevlog_a26jni_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iosdevlog_a26jni_Jni
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iosdevlog_a26jni_Jni_getJniString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
